var e = require("../simpleAndCleanInterfaceForRepl.js")
var repl = e.getRepl()
var youClod = (x) => console.log(require("util").inspect(x, { showHidden: false, depth: null }))
youClod(repl("(123*456)+(789*0.12)"))
youClod(repl("num camila = 5"))
youClod(repl("camila"))
youClod(repl("num young = 7+3*6"))
youClod(repl("young"))
youClod(repl("num havana = camila + young"))
youClod(repl("havana"))
youClod(repl("str youAre = 'autistic'"))
youClod(repl("((1+2)*(3+(4*5)))+havana"))
youClod(repl("1+2-3+4-5"))
youClod(repl("7+3*6*7*9"))
youClod(repl("7*3+6*7*9"))
youClod(repl("7+7+8*3+5*3+3"))
youClod(repl("7+7+8*3+5*3+3/3"))
youClod(repl("(7+7+8*3+5*3+3/3)/3"))
youClod(repl("-7+4"))
youClod(repl("4+-7*2"))
youClod(repl("-6+3*-(1+3*3+-(5*3+1))"))
youClod(repl("num potato(p1, p2, p3){num skye = 1;num scotland = 2; return p1+p2+p3+skye+scotland}"))
youClod(repl("potato(1,2,3)"))
youClod(repl("num famine(p1, p2, p3){num skye = 1;num scotland = 2; num add(p1, p2, p3, p4, p5){return p1+p2+p3+p4+p5}; return add(p1,p2,p3,skye,scotland)}"))
youClod(repl("famine(1,2,3)"))
youClod(repl("var closure(multiplier, start){num add(){skye = skye + 1; return skye*multiplier}; num skye = start/multiplier-1; return add}")) // no ++ or += yet, unfortunately
youClod(repl("var    parserReliabilityTest    (  multiplier  , start  )    {   num add  ()  {  skye = skye + 1   ; return skye  *  multiplier  }   ; num skye = start  /  multiplier  -  1  ; return add }  ")) // no ++ or += yet, unfortunately
youClod(repl("var clo = closure(1, 10)"))
youClod(repl("var ver = closure(2, 20)"))
youClod(repl("clo()"))
youClod(repl("ver()"))
youClod(repl("clo()"))
youClod(repl("ver()"))
youClod(repl("clo()"))
youClod(repl("ver()"))
youClod(repl("var rte = parserReliabilityTest (  2  * 3   , 8 * 4   )"))
youClod(repl("rte()"))
youClod(repl("rte()"))
// skye is trapped
youClod(repl("skye"))
youClod(repl("num slowFibonacci(n){if(n < 3){return 1};return slowFibonacci(n-1)+slowFibonacci(n-2)}"))
youClod(repl("slowFibonacci(10)"))
youClod(repl("(if (slowFibonacci(10)==55){1}else{2})+1"))
youClod(repl("if (slowFibonacci(10)==55){1}else{2}"))
youClod(repl("(if (slowFibonacci(10)==55){1}else{2})"))
youClod(repl("num s(n){if(n<3){1}else{s(n-1)+s(n-2)}}"))
youClod(repl("num res = s(10)"))
youClod(repl("if(res==55){1}else{2}"))
youClod(repl("if(res==55){1}else{2}+1"))
youClod(repl("num fastFibonacci(n){num a = 1; num b = 1;num c = 1; while(n>2){c = a+b; a = b; b = c; n = n-1}; return c}"))
youClod(repl("fastFibonacci(1000)"))
youClod(repl("num languageQuirks1(){num n = 0;while(1==1){n=n+1;if(n>5){return 1}};return n}")) // returns 1 (return acts normally)
youClod(repl("num languageQuirks2(){num n = 0;(while(1==1){n=n+1;if(n>5){return 1}});return n}")) // returns 6 (return acts like break when block is parenthesized)
youClod(repl("num languageQuirks3(){num n = 0;1+while(1==1){n=n+1;if(n>5){return 1}};return n}")) // returns 6 (return acts like break when block is implied to be expression)
youClod(repl("languageQuirks1()"))
youClod(repl("languageQuirks2()"))
youClod(repl("languageQuirks3()"))