var e = require("./simpleAndCleanInterfaceForRepl.js")
var repl = e.getRepl()
console.log(repl("(123*456)+(789*0.12)"))
console.log(repl("num camila = 5"))
console.log(repl("camila"))
console.log(repl("num young = 7+3*6"))
console.log(repl("young"))
console.log(repl("num havana = camila + young"))
console.log(repl("havana"))
console.log(repl("str youAre = 'autistic'"))
console.log(repl("((1+2)*(3+(4*5)))+havana"))
console.log(repl("1+2-3+4-5"))
console.log(repl("7+3*6*7*9"))
console.log(repl("7*3+6*7*9"))
console.log(repl("7+7+8*3+5*3+3"))
console.log(repl("7+7+8*3+5*3+3/3"))
console.log(repl("(7+7+8*3+5*3+3/3)/3"))